#include <Arduino.h>

#define DMX_MIN_CHANNELS 192
#define DMX_MAX_CHANNELS 512
#define DMX_MAX_TRANSMIT_INTERVAL_MS 1500
#define DMX_BREAK_LOW_INTERVAL_MICROS 92
#define DMX_BREAK_HIGH_INTERVAL_MICROS 12
